# Generated by Django 5.1 on 2024-08-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Создание в базе данных таблиц спортов:
    американского, обычного футболов и бейсбола
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baseball',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('line', models.DecimalField(decimal_places=2,
                                             max_digits=5)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('line', models.DecimalField(decimal_places=2,
                                             max_digits=5)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Soccer',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('line', models.DecimalField(decimal_places=2,
                                             max_digits=5)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
