# Generated by Django 5.1 on 2024-08-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseball',
            name='version',
        ),
        migrations.RemoveField(
            model_name='football',
            name='version',
        ),
        migrations.RemoveField(
            model_name='soccer',
            name='version',
        ),
    ]
